"""init

Revision ID: 09782da39162
Revises: 
Create Date: 2025-02-05 15:20:50.393495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09782da39162'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'path',
               existing_type=sa.TEXT(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_constraint('categories_parent_id_fkey', 'categories', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('categories_parent_id_fkey', 'categories', 'categories', ['parent_id'], ['id'], ondelete='CASCADE')
    op.alter_column('categories', 'path',
               existing_type=sa.TEXT(),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
