"""remove path

Revision ID: 3c648e6df79c
Revises: e977ad21e51f
Create Date: 2025-02-05 15:49:08.496835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c648e6df79c'
down_revision: Union[str, None] = 'e977ad21e51f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'lft',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('categories', 'rgt',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('categories', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('path', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('categories', 'rgt',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('categories', 'lft',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
