"""add lft rgt

Revision ID: e977ad21e51f
Revises: 09782da39162
Create Date: 2025-02-05 15:21:52.100154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e977ad21e51f'
down_revision: Union[str, None] = '09782da39162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('lft', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('rgt', sa.Integer(), nullable=True))
    op.alter_column('categories', 'path',
               existing_type=sa.TEXT(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'path',
               existing_type=sa.TEXT(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('categories', 'rgt')
    op.drop_column('categories', 'lft')
    # ### end Alembic commands ###
